### ISSUE TITLE
Language option

### ISSUE THREAD

**Issue by MPThLee** [shinycolors/hiori#19]
Currently, Language option is hardcoded but easily changeable.
[dialog/injects.js#L8](https://github.com/shinycolors/hiori/blob/220f577da9b787b4799d18767cb32ad98b89bdaf/src/modules/dialog/injects.js#L8)
[replacer/background.js#L8](https://github.com/shinycolors/hiori/blob/220f577da9b787b4799d18767cb32ad98b89bdaf/src/modules/replacer/background.js#L8)

Can we add options for i18n?
There's a branch already exists which contains Korean images. [#](/shinycolors/hiori/compare/develop...ui_ko)

----
 - [x] Add Language option in setting page.
 - [ ] (Optional) Add Font option for non-japanese, non-english characters.

**Comment by dragonjet** [comment]
will defer adding option to choose font. current options feature only applies to the replacer due to backend obstacles. dialog module is injected directly onto the game's webpage, and thus localStorage is not accessible from its context.
