### ISSUE TITLE
Sakuya Produce 

### ISSUE THREAD

**Issue by mintgreenrose** [shinycolors/hiori#24]
{"messages":[{"ch":"Producer","jp":"（２８３プロダクションに入社して数か月……\r\nいよいよ俺が、アイドルをプロデュースする時が来た）","tl":""},{"ch":"Producer","jp":"（ずっと憧れていた仕事をようやく任されたんだ、\r\nこれから精一杯頑張るぞ！）","tl":""},{"ch":"Producer","jp":"おはようございます！\r\nって、天井社長……？","tl":""},{"ch":"President","jp":"おはよう、お前を待っていたぞ","tl":""},{"ch":"Producer","jp":"（この２８３プロダクションを束ねる\r\n天井社長……あいかわらずダンディな雰囲気だ）","tl":""},{"ch":"President","jp":"お前には今日から、アイドルを\r\nプロデュースしてもらうと伝えていたが……","tl":""},{"ch":"President","jp":"素晴らしい結果を期待させてもらう\r\n私は甘くないぞ","tl":""},{"ch":"Producer","jp":"は、はい！　よろしくお願いします！","tl":""},{"ch":"President","jp":"よろしい。では、仕事の説明ははづきに任せて……","tl":""},{"ch":"Producer","jp":"？　はづきさんはどこにも……あっ！？","tl":""},{"ch":"Producer","jp":"（そ、ソファの裏で誰かが倒れてる！？）","tl":""},{"ch":"Hazuki","jp":"……ふわぁ～？\r\nなんですか～急に大きな声出して～……","tl":""},{"ch":"President","jp":"は、はづき……なぜ床で寝ているんだ","tl":""},{"ch":"Hazuki","jp":"すみません、ソファへ着く前に\r\n眠気に負けてしまいまして～……","tl":""},{"ch":"President","jp":"せっかくまじめな雰囲気を出したというのに……","tl":""},{"ch":"President","jp":"……ともかく！\r\n彼に仕事の説明をしてくれ","tl":""},{"ch":"Hazuki","jp":"はい、もちろんです\r\nプロデューサーさん、どうぞ～","tl":""},{"ch":"Producer","jp":"ありがとうございます\r\n……あいかわらず、わかりやすくまとまってますね、資料","tl":""},{"ch":"Producer","jp":"（はづきさん、こういうところは頼れるんだよな……）","tl":""},{"ch":"Hazuki","jp":"ありがとうございます\r\nそれじゃあ、さっそくお仕事の説明に入りますね～","tl":""},{"ch":"Hazuki","jp":"まず、今回のプロデュースの目標についてですが……","tl":""},{"ch":"Hazuki","jp":"ワンダーアイドルノヴァ・グランプリ……\r\n通称『W.I.N.G.』への出場を目指してください","tl":""},{"ch":"Producer","jp":"『W.I.N.G.』……ですか","tl":""},{"ch":"Hazuki","jp":"はい\r\n新人アイドルの祭典とも言われる、すごいライブなんです","tl":""},{"ch":"Hazuki","jp":"祭典と言われるだけあって、この『W.I.N.G.』は\r\n出場資格を手に入れるまでが厳しいんです……","tl":""},{"ch":"Hazuki","jp":"エントリーしたアイドルは開催前まで、\r\n全４回のシーズンごとに審査を受けます","tl":""},{"ch":"Hazuki","jp":"その時、一定のランクに達していないと、\r\n出場資格を失ってしまうんです","tl":""},{"ch":"Hazuki","jp":"ですので、精一杯頑張っていきましょ～！\r\n私もたくさんサポートさせていただきますね～","tl":""},{"ch":"President","jp":"……少しアドバイスをしておくが、\r\nお前は、２８３プロダクションのプロデューサーだ","tl":""},{"ch":"President","jp":"担当アイドルと他のアイドルたちを\r\n交流させることも重要になってくる","tl":""},{"ch":"President","jp":"互いに影響しあうことで目指せる高みもあるだろう","tl":""},{"ch":"President","jp":"まあ、まずは思うようにやってみるといい\r\n結果がついてくるかは、お前とアイドルの頑張り次第だ","tl":""},{"ch":"Hazuki","jp":"では、そろそろお仕事に移ってもらいましょうか\r\n今回プロデュースするアイドルは──","tl":""},{"ch":"Producer","jp":"（社長もいきなりだな\r\n『スカウトしてこい』だなんて……）","tl":""},{"ch":"Producer","jp":"とりあえず、人通りが多いところに行ってみるか","tl":""},{"ch":"Producer","jp":"（ん、あそこでやってるのは雑誌の撮影か\r\nあのモデル……なんだか目を引かれるな）","tl":""},{"ch":"カメラマン","jp":"よし、今日の撮影はここまでにしておこう","tl":""},{"ch":"？？？","jp":"お疲れ様です、ありがとうございました","tl":""},{"ch":"Producer","jp":"（あのモデル……\r\n凛としてとてもかっこいいな……）","tl":""},{"ch":"？？？","jp":"やあ、私に何か用かな？","tl":""},{"ch":"Producer","jp":"えっ、あ、ああ……","tl":""},{"ch":"？？？","jp":"私を見ていたと思ったのだけど……\r\n気のせいだったかな","tl":""},{"ch":"Producer","jp":"いや、気のせいじゃないぞ。確かに君を見ていたよ\r\nあ、俺は芸能プロダクションに勤めている者で……","tl":""},{"ch":"？？？","jp":"フフ。なるほど\r\nつまり、私をスカウトしたいのかい？","tl":""},{"ch":"Producer","jp":"ああ、さっきの撮影を見ていて素質を感じたんだ\r\n君、アイドルになる気はないかい？","tl":""},{"ch":"？？？","jp":"……へぇ、私がアイドルか","tl":""},{"ch":"Producer","jp":"ああ\r\nぜひ君をアイドルとして、プロデュースしたいんだ！","tl":""},{"ch":"？？？","jp":"でも、見てのとおり\r\n私はアイドルらしくはないんじゃないかな？","tl":""},{"ch":"？？？","jp":"もっと、アイドルにふさわしい子はいっぱいいるのに\r\nどうして、わざわざ私なんだい？","tl":""},{"ch":"Producer","jp":"君だからこそ、プロデュースしたいんだ！\r\n君には、アイドルの素質が十二分にある！","tl":""},{"ch":"Producer","jp":"堂々としていて、自分の魅せ方を知っている\r\nそれだけでも、すごい武器になるぞ！","tl":""},{"ch":"Producer","jp":"ぜひ、俺に君をプロデュースさせてほしい！","tl":""},{"ch":"？？？","jp":"……なるほどね、フフ\r\nよし……その誘い、受けさせてもらうよ","tl":""},{"ch":"Producer","jp":"本当か！？\r\nでも、こんなに早く決めていいのか？","tl":""},{"ch":"？？？","jp":"クス\r\n自分からスカウトしてきたのに、おかしなことを言うね","tl":""},{"ch":"Producer","jp":"わ、悪い\r\nずいぶんあっさりしていたから、つい……","tl":""},{"ch":"？？？","jp":"フフ。アナタの私を思う気持ちに、\r\n応えたいと思っただけだよ","tl":""},{"ch":"？？？","jp":"つまり私を選んだアナタに\r\n興味を引かれたんだ","tl":""},{"ch":"Producer","jp":"それは光栄だけど……","tl":""},{"ch":"Producer","jp":"（なんだか、距離が近すぎるような……）","tl":""},{"ch":"？？？","jp":"どうかしたのかい？","tl":""},{"ch":"Producer","jp":"い、いや、なんでもない\r\nそれじゃあ、事務所で詳しい話をさせてもらえるかな？","tl":""},{"ch":"？？？","jp":"ああ、よろしく頼むよ","tl":""},{"ch":"Sakuya","jp":"改めて、私は白瀬咲耶だ\r\n私たちの新たなる第１歩を、共に踏み出そう","tl":""}]}

**Comment by mintgreenrose** [comment]
{"messages":[{"ch":"Producer","jp":"咲耶はなんというか、神秘的な感じだよな\r\nあまり生活感がないというか……","tl":""},{"ch":"Sakuya","jp":"クス、\r\n私の生活が気になるのかい？","tl":""},{"ch":"Producer","jp":"そうだな。プロデューサーとして、気になるところだ","tl":""},{"ch":"Sakuya","jp":"じゃあ、\r\nアナタは私がどういう生活をしていると思う？","tl":""},{"ch":"Sakuya","jp":"フフ、そこまで真剣に考えてくれてうれしいよ","tl":""},{"ch":"Sakuya","jp":"その想像が当たっているか……\r\nこれからじっくりと確かめてほしいな","tl":""},{"ch":"Producer","jp":"（よし、楽しく話せたな）","tl":""},{"ch":"Sakuya","jp":"フフ、実はそうなんだ\r\n家事なんかも自分でやるしね","tl":""},{"ch":"Sakuya","jp":"ファンの子たちが知ったら、意外だと思うだろうね","tl":""},{"ch":"Producer","jp":"（まぁ、普通に話せたかな）","tl":""},{"ch":"Sakuya","jp":"どうして私の生活が派手だなんて思うんだい？","tl":""},{"ch":"Sakuya","jp":"私は、プロデューサーに\r\nそういう印象を与えてしまっているのかな……","tl":""},{"ch":"Producer","jp":"（うっ……しまった。別のことを言えば良かったな……）","tl":""}]}

**Comment by mintgreenrose** [comment]
{"messages":[{"ch":"Sakuya","jp":"歌のパフォーマンスについて\r\nより良く見せる方法を勉強したいんだ","tl":""},{"ch":"Sakuya","jp":"ボーカルレッスンの時間を\r\n今週で調整をしてもらっていいかな？","tl":""},{"ch":"Sakuya","jp":"フフ、ありがとう\r\nプロデューサーならそう言ってくれると思ったよ","tl":""},{"ch":"Sakuya","jp":"そうか……仕方ないね","tl":""}]}

**Comment by mintgreenrose** [comment]
{"messages":[{"ch":"Producer","jp":"咲耶、ユニットのみんなとは楽しくやれているか？","tl":""},{"ch":"Sakuya","jp":"ああ、誰かと一緒にいることは元々好きだが、\r\nユニットのみんなといるのは、特別楽しいね","tl":""},{"ch":"Sakuya","jp":"レッスンや仕事だけでなく、\r\nプライベートでも一緒にいることが増えてきたよ","tl":""},{"ch":"Producer","jp":"（ユニットの仲がいいのは良いことだな……）","tl":""},{"ch":"Sakuya","jp":"プロデューサーも一緒にか……うん\r\nみんなとの絆も深くなっていいかもしれないね","tl":""},{"ch":"Sakuya","jp":"今度みんなで集まる時は、\r\nプロデューサーにも声をかけるよ","tl":""},{"ch":"Producer","jp":"（よし、楽しく話せたな）","tl":""},{"ch":"Sakuya","jp":"もちろん伝えてみせるさ\r\nそれが私の使命だからね","tl":""},{"ch":"Sakuya","jp":"プロデューサーにはもう、届いているかい？","tl":""},{"ch":"Producer","jp":"（まぁ、普通に話せたかな）","tl":""},{"ch":"Sakuya","jp":"確かに私はあまり疲れないが、\r\nほかのみんなはどうだろうね？","tl":""},{"ch":"Sakuya","jp":"あまりはしゃぎすぎるのも、良くなかったかな\r\n今度からもっとみんなを気遣うよ","tl":""},{"ch":"Producer","jp":"（うっ……しまった。別のことを言えば良かったな……）","tl":""}]}

**Comment by mintgreenrose** [comment]
{"messages":[{"ch":"Sakuya","jp":"今日の撮影では、このリップクリームを使うんだね","tl":""},{"ch":"Producer","jp":"ああ。広告スペースは小さいが、\r\n女性誌に載るんだ","tl":""},{"ch":"Producer","jp":"アンティーカだってまだまだ駆け出しなのに、\r\nこんな仕事が来るのはすごいことだぞ！","tl":""},{"ch":"Sakuya","jp":"フフ。プロデューサーが\r\nがんばってくれているおかげだよ","tl":""},{"ch":"Sakuya","jp":"私ひとりの力では、こんな仕事は到底いただけなかった\r\nプロデューサーがいてくれたからこそだよ","tl":""},{"ch":"Sakuya","jp":"だからアナタの期待に応えられるよう、がんばるよ","tl":""},{"ch":"Producer","jp":"ああ、期待してるぞ！","tl":""},{"ch":"Sakuya","jp":"フフ。ありがとう、プロデューサー","tl":""},{"ch":"Sakuya","jp":"……しかし、モデルの経験はあっても\r\nこうした広告の撮影は初めてだからね","tl":""},{"ch":"Sakuya","jp":"広告は自分ではなく\r\n商品の魅力を伝えることが重要なはず……","tl":""},{"ch":"Sakuya","jp":"商品を魅力的に見せるには\r\nどんなポーズや表情で撮影に臨めばいいのだろうか……","tl":""},{"ch":"Sakuya","jp":"プロデューサーは、どう思う？","tl":""},{"ch":"Producer","jp":"そうだな。俺は咲耶の魅力が伝われば、\r\nおのずと商品の魅力も伝えられると思う","tl":""},{"ch":"Producer","jp":"だから、今日の咲耶は……","tl":""},{"ch":"Sakuya","jp":"クス。嬉しいことを言ってくれるね","tl":""},{"ch":"Sakuya","jp":"それじゃあ、プロデューサーの言うとおり\r\nありのままの私で行ってくるとしよう","tl":""},{"ch":"Producer","jp":"お疲れ\r\n初めての広告撮影、どうだった？","tl":""},{"ch":"Sakuya","jp":"幸い、カメラマンの方から褒めていただけたよ","tl":""},{"ch":"Sakuya","jp":"『落ち着いたまなざしと化粧品がマッチして、\r\nとても印象的な写真が撮れた』ってね","tl":""},{"ch":"Producer","jp":"すごいじゃないか！　\r\n今回のカメラマンは、厳しいって有名な人だったんだぞ","tl":""},{"ch":"Sakuya","jp":"ああ、そうだったみたいだね","tl":""},{"ch":"Sakuya","jp":"上手くいったのは、プロデューサーのアドバイスのおかげだ","tl":""},{"ch":"Sakuya","jp":"これからも頼りにさせてもらうよ","tl":""},{"ch":"Producer","jp":"（この距離感に慣れるのは、もう少し先かな……）","tl":""},{"ch":"Sakuya","jp":"なるほど。商品も落ち着いた色味だから\r\nそのほうがぴったり合いそうだね","tl":""},{"ch":"Producer","jp":"ああ\r\nそれに咲耶のカッコよさも際立つしな","tl":""},{"ch":"Sakuya","jp":"フフ\r\nそう言ってもらえると、自信が持てるよ","tl":""},{"ch":"Sakuya","jp":"それじゃあ、プロデューサーの言葉を意識して\r\n撮影に挑むとしよう","tl":""},{"ch":"Producer","jp":"お疲れ！　良い撮影だったな\r\n女性スタッフが黄色い声を上げてたぞ","tl":""},{"ch":"Sakuya","jp":"クス、それは光栄だね","tl":""},{"ch":"Sakuya","jp":"プロデューサーの的確なアドバイスがあったからこそだよ","tl":""},{"ch":"Producer","jp":"いや、女性スタッフをあれだけ喜ばせられたのは\r\n咲耶のクールな魅力があってこそだ","tl":""},{"ch":"Producer","jp":"商品のターゲットは女性だからな\r\n咲耶だからこそ、できた仕事だぞ","tl":""},{"ch":"Sakuya","jp":"フフ。そう言ってもらえると、うれしいな……","tl":""},{"ch":"Sakuya","jp":"これからもよろしく頼むよ、プロデューサー","tl":""},{"ch":"Producer","jp":"ああ！\r\nこれからの咲耶の活躍に、期待しているぞ！","tl":""},{"ch":"Producer","jp":"今回は化粧品の広告だからな\r\n女性的な魅力を押し出した方がいいだろう","tl":""},{"ch":"Sakuya","jp":"色っぽい……女性的、か……","tl":""},{"ch":"Producer","jp":"難しいことは考えなくていい\r\nそのままの咲耶がもう、魅力的な女性だからな","tl":""},{"ch":"Sakuya","jp":"……フフ、そうまっすぐ言われると\r\n少し照れてしまうね","tl":""},{"ch":"Sakuya","jp":"ありがとう\r\nこれで迷いなく撮影に挑むことができるよ","tl":""},{"ch":"Producer","jp":"良かったな、咲耶\r\nクライアントからあんなに大好評で","tl":""},{"ch":"Sakuya","jp":"ああ、次はもっと大きい広告で、なんて……\r\n嬉しいけど、驚いたよ","tl":""},{"ch":"Sakuya","jp":"しかしそれなら、女性的な魅力を\r\nもっと高めないといけないかもしれないね","tl":""},{"ch":"Producer","jp":"咲耶は、今のままでも充分魅力的だと思うけどな……","tl":""},{"ch":"Sakuya","jp":"いいや、まだまだだよ。みんなを喜ばせるためにも\r\n私は、もっともっと女性的な魅力を追求していくよ！","tl":""},{"ch":"Producer","jp":"（何事にも一生懸命だし、プロ意識も高い……\r\n咲耶の今後が楽しみだな……）","tl":""}]}

**Comment by dragonjet** [comment]
Sakuya Produce moved to shinycolors/sc3-translations#40
