### ISSUE TITLE
Broken images after maintanance.

### ISSUE THREAD

**Issue by MPThLee** [shinycolors/hiori#34]
* Can not access gasha, event, shop, idol pages
    * It seems like patched images' resolution is lower than updated images.
![Image](https://user-images.githubusercontent.com/26970092/40298664-d7ad1dca-5d1e-11e8-8aae-ea6d73d9846a.png)

 * Updated tr images which after maintanance.
    - [ ] `0369993d697bb1b162ae2d8229960eb25405da4ee7d7285658635b686fd0fdb3.png` (Gasha Page)
    - [ ] `06cc638c7e37b9b4f39fa5e8c9c184b483367b279733ba08b99b11ba3b7c02b7.png` (Produce)
    - [ ] `a5780581d35525729e3fbf6820cf9efaaffcc5e9757c80cd184b6e86b6451afd.png` (Shop/Idol Buttons)
    - [ ] `e23f860a80c8560ed3fb3ce2d6b537f142bddd42edbd46fa2f03de35bf5c3453.png` (Event Page)

**Comment by eonisbuffering** [comment]
Confirmed Accessible:
Missions, Items, Fes, Everything except Produce Unit page in Idol, News

Confirmed Unaccessible:
Produce, Produce Unit page in Idol, Gacha, Shop, Event page
